Text_BootUpPC:
	.string "{PLAYER} booted up the PC.$"

gText_WhichPCShouldBeAccessed::
	.string "Which PC should be accessed?$"

gText_AccessedSomeonesPC::
	.string "Accessed {PLAYER}'s POKéMON Storage.$"

gText_StorageSystemOpened::
	.string "POKéMON Storage System opened.$"

gText_AccessedPlayersPC::
	.string "Accessed {PLAYER}'s Item Storage.$"

gText_AccessedLanettesPC::
	.string "Accessed {PLAYER}'s POKéMON Storage.$"
