HealingHut_MapScripts::
	.byte 0


# 3 "data/maps/HealingHut/scripts.pory"

# 4 "data/maps/HealingHut/scripts.pory"
EventScript_Flash_Heal::
# 5 "data/maps/HealingHut/scripts.pory"
lockall
# 6 "data/maps/HealingHut/scripts.pory"
fadescreen FADE_TO_WHITE
# 7 "data/maps/HealingHut/scripts.pory"
special HealPlayerParty
# 8 "data/maps/HealingHut/scripts.pory"
fadescreen FADE_FROM_WHITE
# 9 "data/maps/HealingHut/scripts.pory"
release
# 10 "data/maps/HealingHut/scripts.pory"
end
